name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
    - '**'
  workflow_dispatch:
    branches:
    - '**'


jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.8']
        toxenv: [py, quality]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
    - name: Run check-keywords
      # This will analyze django apps to see if any of the model fields
      # have names that are on a list of reseverd keywords and should not
      # be used.
      run: |
        pip install --upgrade pip click
        pip install pip-tools
        pip install -r requirements/base.txt
        cookiecutter --no-input cookiecutter-django-ida
        cd repo_name
        make upgrade
        pip install -r requirements/production.txt
        make check_keywords
